from .frsm_01 import test_id_presence_and_resolves
from .frsm_01 import test_id_common_schema
from .frsm_01 import test_id_associated_with_software
from .frsm_03 import test_version_number_in_metadata
from .frsm_03 import test_has_releases
from .frsm_03 import test_release_id_and_version
from .frsm_03 import test_semantic_versioning_standard
from .frsm_03 import test_version_scheme
from .frsm_03 import test_latest_release_consistency
from .frsm_04 import test_metadata_exists
from .frsm_04 import test_readme_exists
from .frsm_04 import test_title_description
from .frsm_04 import test_descriptive_metadata
from .frsm_04 import test_codemeta_exists
from .frsm_05 import test_repo_status
from .frsm_05 import test_contact_support_documentation
from .frsm_05 import test_software_documentation
from .frsm_05 import test_active_communication_channels
from .frsm_06 import test_authors
from .frsm_06 import test_contributors
from .frsm_06 import test_authors_orcids
from .frsm_07 import test_identifier_in_readme_citation
from .frsm_07 import test_identifier_resolves_to_software
from .frsm_08 import test_metadata_record_in_software_heritage
from .frsm_08 import test_metadata_record_in_zenodo
from .frsm_09 import test_is_github_repository
from .frsm_12 import test_reference_publication
from .frsm_13 import test_dependencies_declared
from .frsm_13 import test_installation_instructions
from .frsm_13 import test_dependencies_have_version
from .frsm_13 import test_dependencies_in_machine_readable_file
from .frsm_14 import test_presence_of_tests
from .frsm_14 import test_github_action_tests
from .frsm_15 import test_has_license
from .frsm_15 import test_license_spdx_compliant
from .frsm_16 import test_license_info_in_metadata_files
from .frsm_17 import test_commit_history
from .frsm_17 import test_commits_linked_issues
from .misc import test_has_citation
from .misc import test_repository_workflows
from .misc import test_has_issue_tracker
from .misc import test_has_contribution_guidelines
from .misc import test_containerized
